#!/bin/bash

#Parameters
PRODUCT_HOME=/__ROOT_DIR__/__PLUGIN_DIR__

echo "Post installation process started"

echo "Change permissions in product home"
cd ${PRODUCT_HOME}
sudo chmod -R 777 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

echo "Post installation process finished"
