#!/bin/bash

#Parameters
PRODUCT_HOME=/Library/__ROOT_DIR__/__APP_ID__

echo "Post installation process started"

Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

echo "Post installation process finished"
