# Basically, on PR open/update, download all files from release in a certain repo, then put them in the release as pre-release.
# Still need to number the version manually.
name: "Create release build for Cinema4D-Plugin"
on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-event]

# OBI_AC_PAT_ORG is created by Obi and needs to be renewed every so often when it expires.
# send him to `https://github.com/settings/personal-access-tokens/798287` and have him click the regenerate button
# To update, have Obi navigate to "UNOMI Solutions -> settings -> secrets and stuff -> actions" and then update the value (note that 
# this is in the ORGANIZATION settings, while his token is in PERSONAL account settings)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v3

      - name: Download latest Release as release.zip
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'UNOMi-Solutions/Cinema4D-Plugin'
          regex: true
          file: ".*-release.zip"
          token: ${{ secrets.OBI_AC_PAT_ORG }}

      - name: Unzip Files into release dir
        run: unzip "*-release.zip" -d release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: C4D-LS-1.*
          prerelease: true
          files: |
            release/*
          
